# Generated by Django 6.0.4 on 2026-06-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(default=1200, verbose_name="Rating (Elo)"),
                ),
                (
                    "games_played",
                    models.IntegerField(default=0, verbose_name="Partidas Jogadas"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_profile",
                        to="profiles.profile",
                        verbose_name="Perfil Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Jogador",
                "verbose_name_plural": "Perfis de Jogadores",
            },
        ),
    ]
