# Generated by Django 6.0.4 on 2026-06-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_playerprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promoted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Promovido em"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to="profiles.profile",
                        verbose_name="Perfil Base",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Promovido por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil Administrativo",
                "verbose_name_plural": "Perfis Administrativos",
            },
        ),
    ]
