# Generated by Django 6.0.4 on 2026-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                default="dark", max_length=20, verbose_name="Preferência de Tema"
            ),
        ),
    ]
