# Generated by Django 6.0.4 on 2026-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="theme_preference",
            field=models.CharField(
                choices=[("light", "Claro"), ("dark", "Escuro"), ("system", "Sistema")],
                default="system",
                max_length=10,
                verbose_name="Preferência de tema",
            ),
        ),
    ]
