# Generated by Django 6.0.4 on 2026-05-31 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_theme_preference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="theme_preference",
        ),
    ]
