# Generated by Django 6.0.4 on 2026-07-13 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_gamehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamehistory",
            name="modality",
            field=models.CharField(
                choices=[("bullet", "Bullet"), ("blitz", "Blitz"), ("rapid", "Rápido")],
                default="blitz",
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="ModalityRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("bullet", "Bullet"),
                            ("blitz", "Blitz"),
                            ("rapid", "Rápido"),
                        ],
                        max_length=6,
                    ),
                ),
                ("rating", models.FloatField(default=1500.0, verbose_name="Rating")),
                (
                    "deviation",
                    models.FloatField(default=350.0, verbose_name="Desvio (RD)"),
                ),
                (
                    "volatility",
                    models.FloatField(default=0.06, verbose_name="Volatilidade"),
                ),
                (
                    "games_played",
                    models.IntegerField(default=0, verbose_name="Partidas jogadas"),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modality_ratings",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rating por modalidade",
                "verbose_name_plural": "Ratings por modalidade",
                "unique_together": {("profile", "modality")},
            },
        ),
    ]
