# Generated by Django 6.0.4 on 2026-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_seed_modality_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Onboarding concluído em"
            ),
        ),
    ]
