# Generated by Django 6.0.4 on 2026-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_grandfather_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Stripe Customer"
            ),
        ),
    ]
