# Generated by Django 6.0.4 on 2026-07-21 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_backfill_missing_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignWinLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Iniciante"),
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                            ("master", "Mestre"),
                        ],
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_win_log",
                        to="users.gamehistory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampaignProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Iniciante"),
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                            ("master", "Mestre"),
                        ],
                        max_length=8,
                    ),
                ),
                ("wins", models.IntegerField(default=0, verbose_name="Vitórias")),
                (
                    "unlocked",
                    models.BooleanField(default=False, verbose_name="Desbloqueado"),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Desbloqueado em"
                    ),
                ),
                (
                    "badge_awarded",
                    models.BooleanField(default=False, verbose_name="Selo concedido"),
                ),
                (
                    "badge_awarded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Selo concedido em"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_progress",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresso de Campanha",
                "verbose_name_plural": "Progressos de Campanha",
                "unique_together": {("profile", "level")},
            },
        ),
    ]
