# Generated by Django 6.0.4 on 2026-08-08 01:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_gamehistory_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="ID público",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="ID no node-api",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("ai", "vs IA"), ("online", "Online")], max_length=6
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("bullet", "Bullet"),
                            ("blitz", "Blitz"),
                            ("rapid", "Rápido"),
                        ],
                        default="blitz",
                        max_length=6,
                    ),
                ),
                (
                    "white_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "black_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "ai_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Iniciante"),
                            ("easy", "Fácil"),
                            ("medium", "Médio"),
                            ("hard", "Difícil"),
                            ("master", "Mestre"),
                        ],
                        max_length=8,
                        null=True,
                        verbose_name="Nível da IA",
                    ),
                ),
                (
                    "ai_color",
                    models.CharField(
                        blank=True,
                        choices=[("w", "Brancas"), ("b", "Pretas")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "moves",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Lances (SAN)"
                    ),
                ),
                (
                    "ply_count",
                    models.IntegerField(default=0, verbose_name="Lances jogados"),
                ),
                (
                    "moves_truncated",
                    models.BooleanField(default=False, verbose_name="Lances truncados"),
                ),
                (
                    "initial_fen",
                    models.CharField(
                        blank=True,
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=100,
                    ),
                ),
                ("final_fen", models.CharField(blank=True, default="", max_length=100)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("white", "Brancas"),
                            ("black", "Pretas"),
                            ("draw", "Empate"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "termination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("checkmate", "Xeque-mate"),
                            ("stalemate", "Afogamento"),
                            ("repetition", "Repetição"),
                            ("insufficient", "Material insuficiente"),
                            ("draw", "Empate"),
                            ("agreement", "Acordo"),
                            ("resign", "Desistência"),
                            ("abandon", "Abandono"),
                            ("timeout", "Tempo esgotado"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("time_control", models.IntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "black_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games_as_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
                "ordering": ["-ended_at"],
            },
        ),
        migrations.AddField(
            model_name="gamehistory",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_entries",
                to="users.game",
                verbose_name="Partida",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["white_player", "-ended_at"],
                name="users_game_white_p_dc43cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["black_player", "-ended_at"],
                name="users_game_black_p_2f55d4_idx",
            ),
        ),
    ]
