# Generated by Django 6.0.4 on 2026-08-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_game_gamehistory_game_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("analisando", "Analisando"),
                            ("pronta", "Pronta"),
                            ("falhou", "Falhou"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("params_version", models.IntegerField(default=1)),
                ("engine_depth", models.IntegerField(blank=True, null=True)),
                ("engine_movetime", models.IntegerField(blank=True, null=True)),
                ("engine_id", models.CharField(blank=True, default="", max_length=60)),
                ("white_accuracy", models.FloatField(blank=True, null=True)),
                ("black_accuracy", models.FloatField(blank=True, null=True)),
                ("white_avg_loss", models.IntegerField(blank=True, null=True)),
                ("black_avg_loss", models.IntegerField(blank=True, null=True)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("turning_point_ply", models.IntegerField(blank=True, null=True)),
                ("moves", models.JSONField(blank=True, default=list)),
                ("analyzed_plies", models.IntegerField(default=0)),
                ("attempts", models.IntegerField(default=0)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis",
                        to="users.game",
                        verbose_name="Partida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise de partida",
                "verbose_name_plural": "Análises de partidas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "leased_until"],
                        name="users_gamea_status_3707a3_idx",
                    )
                ],
            },
        ),
    ]
