# Generated by Django 6.0.4 on 2026-08-15 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_gameanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameLLMFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gerando", "Gerando"),
                            ("pronto", "Pronto"),
                            ("erro", "Erro"),
                        ],
                        default="gerando",
                        max_length=10,
                    ),
                ),
                ("sections", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.TextField(blank=True, default="")),
                ("prompt_version", models.IntegerField(default=1)),
                ("model_name", models.CharField(blank=True, default="", max_length=60)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("cached_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                (
                    "failure_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_feedback",
                        to="users.gameanalysis",
                        verbose_name="Análise",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="llm_feedbacks_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário da partida",
                "verbose_name_plural": "Comentários das partidas",
                "ordering": ["-created_at"],
            },
        ),
    ]
