# Generated by Django 6.0.4 on 2026-08-15 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_gamellmfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=80, verbose_name="Nome")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=40)),
                ("category", models.CharField(blank=True, default="", max_length=20)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("game_finished", "Fim de partida"),
                            ("puzzle_solved", "Problema resolvido"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("win_count", "Total de vitórias"),
                            ("rated_win_count", "Vitórias valendo rating"),
                            ("games_played", "Partidas jogadas"),
                            ("win_streak", "Vitórias seguidas"),
                            ("fast_checkmate", "Xeque-mate rápido"),
                            ("puzzle_streak", "Dias seguidos resolvendo problema"),
                        ],
                        max_length=30,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Ordem de exibição"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conquista",
                "verbose_name_plural": "Conquistas",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlocks",
                        to="users.achievementdefinition",
                    ),
                ),
                (
                    "source_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="achievements_unlocked",
                        to="users.gamehistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conquista do usuário",
                "verbose_name_plural": "Conquistas dos usuários",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
