# Generated by Django 6.0.4 on 2026-08-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_achievement_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gamehistory",
            index=models.Index(
                fields=["user", "-played_at"], name="users_gameh_user_id_567b8d_idx"
            ),
        ),
    ]
