# Generated by Django 6.0.4 on 2026-08-17 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_device_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="modality",
            field=models.CharField(
                choices=[
                    ("bullet", "Bullet"),
                    ("blitz", "Blitz"),
                    ("rapid", "Rápido"),
                    ("corr", "Correspondência"),
                ],
                default="blitz",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="gamehistory",
            name="modality",
            field=models.CharField(
                choices=[
                    ("bullet", "Bullet"),
                    ("blitz", "Blitz"),
                    ("rapid", "Rápido"),
                    ("corr", "Correspondência"),
                ],
                default="blitz",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="modalityrating",
            name="modality",
            field=models.CharField(
                choices=[
                    ("bullet", "Bullet"),
                    ("blitz", "Blitz"),
                    ("rapid", "Rápido"),
                    ("corr", "Correspondência"),
                ],
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="CorrespondenceGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando aceite"),
                            ("active", "Em andamento"),
                            ("finished", "Terminada"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                (
                    "time_control_days",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 dia por lance"),
                            (3, "3 dias por lance"),
                            (7, "7 dias por lance"),
                        ]
                    ),
                ),
                (
                    "fen",
                    models.CharField(
                        default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                        max_length=100,
                    ),
                ),
                ("moves", models.JSONField(blank=True, default=list)),
                (
                    "turn",
                    models.CharField(
                        choices=[("w", "Brancas"), ("b", "Pretas")],
                        default="w",
                        max_length=1,
                    ),
                ),
                ("last_move_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_deadline",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("white", "Brancas"),
                            ("black", "Pretas"),
                            ("draw", "Empate"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "termination",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("checkmate", "Xeque-mate"),
                            ("stalemate", "Afogamento"),
                            ("repetition", "Repetição"),
                            ("insufficient", "Material insuficiente"),
                            ("draw", "Empate"),
                            ("agreement", "Acordo"),
                            ("resign", "Desistência"),
                            ("abandon", "Abandono"),
                            ("timeout", "Tempo esgotado"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "black_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_as_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "challenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_challenges_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_as_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida do Modo Turno",
                "verbose_name_plural": "Partidas do Modo Turno",
                "ordering": ["current_deadline"],
                "indexes": [
                    models.Index(
                        fields=["white_player", "status"],
                        name="users_corre_white_p_33680e_idx",
                    ),
                    models.Index(
                        fields=["black_player", "status"],
                        name="users_corre_black_p_fc371a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CorrespondenceQueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_control_days",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 dia por lance"),
                            (3, "3 dias por lance"),
                            (7, "7 dias por lance"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correspondence_queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila do Modo Turno",
                "verbose_name_plural": "Filas do Modo Turno",
                "unique_together": {("user", "time_control_days")},
            },
        ),
    ]
