# Generated by Django 6.0.4 on 2026-06-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0002_seed_puzzles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puzzle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userpuzzleprogress",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
