# Generated by Django 6.0.4 on 2026-07-20 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0003_alter_puzzle_id_alter_userpuzzleprogress_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="puzzle",
            options={
                "ordering": ["rating", "id"],
                "verbose_name": "Problema",
                "verbose_name_plural": "Problemas",
            },
        ),
        migrations.AlterModelOptions(
            name="userpuzzleprogress",
            options={
                "verbose_name": "Progresso de Problema",
                "verbose_name_plural": "Progressos de Problema",
            },
        ),
    ]
