# Generated by Django 6.0.4 on 2026-07-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0004_alter_puzzle_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpuzzleprogress",
            name="daily_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Tentativas de hoje"
            ),
        ),
        migrations.AddField(
            model_name="userpuzzleprogress",
            name="daily_attempts_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data das tentativas"
            ),
        ),
        migrations.AddField(
            model_name="userpuzzleprogress",
            name="exhausted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tentativas esgotadas em"
            ),
        ),
        migrations.CreateModel(
            name="DailyPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_appearances",
                        to="puzzles.puzzle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Problema do dia",
                "verbose_name_plural": "Problemas do dia",
                "ordering": ["-date"],
            },
        ),
    ]
